[package]
org = "ballerinax"
name = "persist.redis"
version = "0.2.0"
authors = ["Ballerina"]
keywords = ["persist", "redis", "experimental"]
repository = "https://github.com/ballerina-platform/module-ballerinax-persist.redis"
license = ["Apache-2.0"]
distribution = "2201.10.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "persist.redis-native"
version = "0.2.0"
path = "../native/build/libs/persist.redis-native-0.2.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist-native"
version = "1.4.0"
path = "./lib/persist-native-1.4.0-20240808-102300-3b855e5.jar"
